# Generated by Django 3.1.2 on 2020-10-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Laundry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formnames',
            name='subject',
        ),
    ]
