# Generated by Django 3.1.2 on 2020-10-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Laundry', '0002_remove_formnames_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='formnames',
            name='number',
            field=models.IntegerField(default=1234567),
        ),
    ]
