# Generated by Django 3.1.2 on 2020-10-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Laundry', '0004_subscribtionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('numb', models.IntegerField()),
                ('services', models.CharField(max_length=222)),
                ('serviceman', models.CharField(max_length=222)),
            ],
        ),
        migrations.RenameField(
            model_name='subscribtionmodel',
            old_name='Subscribe',
            new_name='subscribe',
        ),
    ]
