# Generated by Django 3.1.2 on 2020-10-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Laundry', '0005_auto_20201004_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribtionModel',
        ),
    ]
